Cleaned up mojo binding
openhab/openhab1-addons pull request #3623
Opened 2015-12-29 21:19 UTC by sipvoip

Builds and works.

2015-12-30 20:19 UTC, teichsta commented
Thanks for this contribution @sipvoip. Since we are in the preparations of the 1.8 release we won't be able to review this PR before mid of January. I hope for your understanding. Best, Thomas E.-E.

2016-11-18 01:14 UTC, 9037568 requested changes
In addition to these mostly minor changes, need to run all this code through the Eclipse formatter.

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/internal/MojioGenericBindingProvider.java
> +    logger.debug("Configured new item binding as " + bindingConfig);
Use parameterized logging instead of string concatenation.

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/internal/MojioGenericBindingProvider.java
> +	 * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/AbstractFunction.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/AbstractFunction.java
> + * <p>
No need for the paragraph element here.

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/AbstractFunction.java
> + * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/AbstractMessage.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/AbstractMessage.java
> + * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/AbstractRequest.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/AbstractRequest.java
> + * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/AuthorizeRequest.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/AuthorizeRequest.java
> + * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/AuthorizeResponse.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/AuthorizeResponse.java
> + * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/GenericMojioResponse.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/GenericMojioResponse.java
> + * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/GetMojioData.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/GetMojioData.java
> + * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/GetVehicleData.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/GetVehicleData.java
> + * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/MojioStatusResponse.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/MojioStatusResponse.java
> + * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/MojioTimestamp.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/MojioTimestamp.java
> + * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/MojioType.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/MojioType.java
> + * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/Request.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/Request.java
> + * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/Response.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/Response.java
> + * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/VehicleLocation.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/VehicleLocation.java
> + * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/VehicleStatusResponse.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/VehicleStatusResponse.java
> + * @since 1.0
1.9.0

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/VehicleType.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-18 01:14 UTC, 9037568 commented on bundles/binding/org.openhab.binding.mojio/src/main/java/org/openhab/binding/mojio/messages/VehicleType.java
> + * @since 1.0
1.9.0

2021-01-18 20:08 UTC, closed without merging