Binding for Ekozefir air handling unit
openhab/openhab1-addons pull request #3672
Opened 2016-01-02 01:16 UTC by maraszm

Here is the binding for connection openhab and air handling units "Ekozefir" from polish company Ekoklimax-Projekt. Binding works with "Standard" and "Digital" drivers. Program was tested on Cubian (Cubieboard 1) and Debian(x86).

2016-01-02 13:08 UTC, teichsta commented
Thanks @maraszm for this contribution. Please note that we are currently preparing the 1.8 release wich is due on Jan 11th 2016. Hence we are going to review your contribution by end of January earliest. Thanks for your understanding, Thomas E.-E.

2016-11-19 04:22 UTC, 9037568 requested changes
In addition to the inline comments, it appears that the code is missing the src/main/resources folder.

Also, all the code should be run through the Eclipse formatter.

2016-11-19 04:22 UTC, 9037568 commented on bundles/binding/org.openhab.binding.ekozefir/src/main/java/org/openhab/binding/ekozefir/response/extractairlistener/ExtractAirResponseListenerCreator.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-19 04:22 UTC, 9037568 commented on bundles/binding/org.openhab.binding.ekozefir/src/main/java/org/openhab/binding/ekozefir/response/extractairlistener/ExtractAirResponseListenerCreator.java
> + * @since 1.6.0
@since 1.9.0

2016-11-19 04:22 UTC, 9037568 commented on bundles/binding/org.openhab.binding.ekozefir/src/main/java/org/openhab/binding/ekozefir/response/statuslistener/StatusResponseListenerCreator.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-19 04:22 UTC, 9037568 commented on bundles/binding/org.openhab.binding.ekozefir/src/main/java/org/openhab/binding/ekozefir/response/statuslistener/StatusResponseListenerCreator.java
> + * @since 1.6.0
@since 1.9.0

2016-11-19 04:22 UTC, 9037568 commented on bundles/binding/org.openhab.binding.ekozefir/src/main/java/org/openhab/binding/ekozefir/response/supplyairlistener/SupplyAirResponseListenerCreator.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-19 04:22 UTC, 9037568 commented on bundles/binding/org.openhab.binding.ekozefir/src/main/java/org/openhab/binding/ekozefir/response/supplyairlistener/SupplyAirResponseListenerCreator.java
> + * @since 1.6.0
@since 1.9.0

2016-11-19 04:22 UTC, 9037568 commented on bundles/binding/org.openhab.binding.ekozefir/src/main/java/org/openhab/binding/ekozefir/response/targettemplistener/TargetTempResponseListenerCreator.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-19 04:22 UTC, 9037568 commented on bundles/binding/org.openhab.binding.ekozefir/src/main/java/org/openhab/binding/ekozefir/response/targettemplistener/TargetTempResponseListenerCreator.java
> + * @since 1.6.0
@since 1.9.0

2016-11-19 04:22 UTC, 9037568 commented on bundles/binding/org.openhab.binding.ekozefir/src/main/java/org/openhab/binding/ekozefir/response/turninglistener/TurningResponseListenerCreator.java
> + * Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-11-19 04:22 UTC, 9037568 commented on bundles/binding/org.openhab.binding.ekozefir/src/main/java/org/openhab/binding/ekozefir/response/turninglistener/TurningResponseListenerCreator.java
> + * @since 1.6.0
@since 1.9.0

2016-11-19 04:22 UTC, 9037568 commented on bundles/binding/org.openhab.binding.ekozefir/src/main/java/org/openhab/binding/ekozefir/response/EkozefirResponseListenerCreators.java
> +import java.util.HashMap;
This import is never used.

2021-05-16 19:49 UTC, closed without merging