Added CCU2 HomematicIP support
openhab/openhab1-addons pull request #4267
Opened 2016-04-08 14:38 UTC by gerrieg

HomematicIP is disabled by default, to enable it:
```
homematic:homematicIP.enabled=true
```

2016-07-23 11:30 UTC, gerrieg commented
@teichsta 
Any chance to get this merged?

2016-07-26 11:43 UTC, kaikreuzer commented
@gerrieg Please note that @teichsta [is no longer a maintainer of openHAB](https://community.openhab.org/t/growing-the-number-of-active-maintainers/4278/47?u=kai), so you should not wait for him.
Maybe some of the other @openhab/openhab-1-add-ons-maintainers would be willing to review and merge this PR?
In any case, it seems the PR needs to be rebased, before it can be merged - so you might want to do so.

2016-07-27 04:09 UTC, 9037568 commented on bundles/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/common/HomematicConfig.java
> + * # Enables CCU2 HomematicIP support (optional, default is disabled)
I think this should say "default is false"

2016-07-27 04:11 UTC, 9037568 commented on bundles/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/common/HomematicConfig.java
>      }
This is removing a pre-existing public method. Should probably leave this in and mark it as deprecated.

2016-07-27 04:12 UTC, 9037568 commented on distribution/openhabhome/configurations/openhab_default.cfg
> +# Enables CCU2 HomematicIP support (optional, default is disabled)
"default is false"

2016-07-27 05:14 UTC, teichsta commented on bundles/binding/org.openhab.binding.homematic/.classpath
> +	<classpathentry exported="true" kind="lib" path="lib/nanohttpd-2.3.0.jar" sourcepath="/Users/Gerhard/.m2/repository/org/nanohttpd/nanohttpd/2.3.0/nanohttpd-2.3.0-sources.jar"/>
remove sourcepath

2016-07-27 05:22 UTC, teichsta commented
thanks for clarifying @kaikreuzer … nevertheless i am going to review your changes until weekend.

A general question: is this "just" a backport of the OH2 implementation @gerrieg ? This would reduce the review efforts.

Thanks, Thomas E.-E.

2016-07-30 07:49 UTC, gerrieg commented
This is not a backport, i implemented HomematicIP in OH1 first and then i ported it to OH2. But many things are the same.

2016-08-17 11:30 UTC, gerrieg commented
rebase done, now it should be mergeable

2016-08-21 20:17 UTC, marfnk commented
Nice work!
Works with HMIP-WTH Thermostat and a CCU2 like a charm.

2016-10-21 21:56 UTC, danielkr123 commented
Does anyone have an example of an OpenHab item configuration with HomematicIP? I have a HMIP-SWSD smoke alarm but simply adding it as if I had a Homematic device does not work:
`String  SZ_Rauchmelder  " [%b]" <fire>  { binding="address=000A55699D1234, channel=1, parameter=STATE" }`
What makes me doubt that it can work like that is that the serial numbers look quite different to the Homematic devices.

2016-12-04 02:34 UTC, 9037568 requested changes
A couple tiny tweaks. Also please run all source through the eclipse formatter.

2021-05-16 19:49 UTC, closed without merging