New Binding: Girahomeserver Co-Binding
openhab/openhab1-addons pull request #4385
Opened 2016-05-18 08:44 UTC by jochen-mattes

The girahomeserver has an internal CO-Gateway that allows to share communication objects, without having to rely on KNX. This is especially handy for sharing long strings or communication objects / items that are updated frequently.

The interface is documented here: http://www.dacom-ha.de/hshelp/v2_6/en/proj_cogw.html

The implementation follows the example here (python): https://github.com/okohlbacher/pyHSgw

2016-05-18 08:53 UTC, watou commented on bundles/binding/org.openhab.binding.girahomeserver/META-INF/MANIFEST.MF
> +Bundle-Version: 1.8.0-SNAPSHOT.qualifier
1.9.0.qualifier

2016-05-18 08:54 UTC, watou commented on bundles/binding/org.openhab.binding.girahomeserver/META-INF/MANIFEST.MF
> +Bundle-RequiredExecutionEnvironment: J2SE-1.5
JavaSE-1.7

2016-05-18 08:54 UTC, watou commented on bundles/binding/org.openhab.binding.girahomeserver/OSGI-INF/binding.xml
> +    Copyright (c) 2010-2015, openHAB.org and others.
2016

2016-05-18 08:55 UTC, watou commented on bundles/binding/org.openhab.binding.girahomeserver/OSGI-INF/genericbindingprovider.xml
> +    Copyright (c) 2010-2015, openHAB.org and others.
2016 (and all other occurrences)

2016-05-18 08:56 UTC, watou commented on bundles/binding/org.openhab.binding.girahomeserver/pom.xml
> +		<version>1.8.0-SNAPSHOT-SNAPSHOT</version>
1.9.0-SNAPSHOT

2016-05-18 08:57 UTC, watou commented on bundles/binding/org.openhab.binding.girahomeserver/src/main/java/org/openhab/binding/girahomeserver/GiraHomeServerBindingProvider.java
> + * @since 1.8.0-SNAPSHOT
1.9.0

2016-05-18 08:57 UTC, watou commented on bundles/binding/org.openhab.binding.girahomeserver/src/main/java/org/openhab/binding/girahomeserver/internal/GiraHomeServerBinding.java
> + * @since 1.8.0-SNAPSHOT
1.9.0 (and all other occurrences)

2016-05-18 08:59 UTC, watou commented on bundles/binding/org.openhab.binding.girahomeserver/src/main/java/org/openhab/binding/girahomeserver/internal/GiraHomeServerBinding.java
> +		LoggerFactory.getLogger(GiraHomeServerBinding.class);
Please use the project formatting and cleanup rules in the Eclipse IDE -- this line looks like it wraps earlier than the formatter would do?

2016-05-18 09:00 UTC, watou commented on bundles/binding/org.openhab.binding.girahomeserver/src/main/java/org/openhab/binding/girahomeserver/internal/GiraHomeServerBinding.java
> +		// update the internal configuration accordingly
please implement

2016-05-18 09:01 UTC, watou commented on bundles/binding/org.openhab.binding.girahomeserver/src/main/java/org/openhab/binding/girahomeserver/internal/GiraHomeServerBinding.java
> +		logger.debug("execute() method is called!");
Implement AbstractBinding instead of AbstractActiveBinding if you are not going to do anything on the polling interval.

2016-05-18 09:02 UTC, watou commented on bundles/binding/org.openhab.binding.girahomeserver/src/main/java/org/openhab/binding/girahomeserver/internal/GiraHomeServerBinding.java
> +	}
No need to override this or the following method if you are not going to handle commands or updates.

2016-05-18 09:05 UTC, watou commented
Hi Jochen, it looks like this binding doesn't yet do anything?  Please report back after further commits once it's tested and working in your environment.  Thanks!

2016-05-18 09:40 UTC, jochen-mattes commented
sorry, I had pushed the wrong version

2016-05-18 10:28 UTC, watou commented
> sorry, I had pushed the wrong version

No worries, just report back when you believe the PR is ready for review.

2016-05-18 11:55 UTC, jochen-mattes commented
ok, ready. The binding is up and running on two installations.

2016-05-19 06:27 UTC, watou commented
Thanks, @jochen-mattes.  I will take another pass in the coming days.

2016-12-05 03:31 UTC, 9037568 requested changes
In addition to the inline comments, please also:
- run the source through the eclipse formatter
- create a new section in the openhab_default.cfg file for this binding's settings
- create a wiki page documenting the setup for this binding

2021-05-16 19:49 UTC, closed without merging