MegaDevice binding
openhab/openhab1-addons pull request #4401
Opened 2016-05-24 11:48 UTC by Pshatsillo

2016-05-24 12:01 UTC, watou commented
Thanks!

2016-05-25 15:00 UTC, hakan42 commented on bundles/binding/org.openhab.binding.megadevice/src/main/java/org/openhab/binding/megadevice/internal/MegaDeviceBinding.java
> +		String Result = "";
Please rename variable to 'result' to conform with Java coding standards

2016-05-25 15:03 UTC, hakan42 commented on bundles/binding/org.openhab.binding.megadevice/src/main/java/org/openhab/binding/megadevice/internal/MegaDeviceHttpSocket.java
> +			e.printStackTrace();
Please use logger instead of e.printStackTrace()

2016-05-25 15:54 UTC, digitaldan commented on bundles/binding/org.openhab.binding.megadevice/src/main/java/org/openhab/binding/megadevice/internal/MegaDeviceBinding.java
> +	private void ScanPortsScheduler() {
This should also not be capitalized

2016-05-25 17:52 UTC, Pshatsillo commented
Thank you, i have made fixes

2016-12-07 04:06 UTC, 9037568 requested changes
In addition to the inline comments, please also:
- run the source through the Eclipse formatter
- create a wiki page documenting the setup and usage of the binding
- add a section to the [openhab_default.cfg](https://github.com/openhab/openhab/blob/master/distribution/openhabhome/configurations/openhab_default.cfg) file for the settings for the binding

2016-12-07 04:06 UTC, 9037568 commented on bundles/binding/org.openhab.binding.megadevice/META-INF/MANIFEST.MF
> +Bundle-Activator: org.openhab.binding.megadevice.internal.MegaDeviceActivator
Bundle-ActivationPolicy should be set to "lazy"

2016-12-07 04:06 UTC, 9037568 commented on bundles/binding/org.openhab.binding.megadevice/src/main/java/org/openhab/binding/megadevice/internal/MegaDeviceBinding.java
> +											logger.debug(ind + ": " + ResponseParse[ind]);
Use parameterized logging instead of string concatenation.

2016-12-07 04:06 UTC, 9037568 commented on bundles/binding/org.openhab.binding.megadevice/src/main/java/org/openhab/binding/megadevice/internal/MegaDeviceHttpSocket.java
> +public class MegaDeviceHttpSocket extends Thread {
This class needs a doc-comment header including author and since tags.

2016-12-07 04:06 UTC, 9037568 commented on bundles/binding/org.openhab.binding.megadevice/src/main/java/org/openhab/binding/megadevice/internal/MegadeviceHttpServer.java
> +public class MegadeviceHttpServer extends Thread {
This class needs a doc-comment added including author and since tags.

2016-12-07 10:00 UTC, Pshatsillo commented
Thank you for very much Your fixes! I have a question about Wiki. Should i just press link (https://github.com/openhab/openhab/wiki/_new) on main wiki page and create new? Thank you. Sorry for dumb questions

2016-12-07 10:33 UTC, watou commented
> Should i just press link (https://github.com/openhab/openhab/wiki/_new) on main wiki page and create new? Thank you. Sorry for dumb questions

Not a dumb question at all!  Yes please, and please name the wiki page "MegaDevice Binding".

2016-12-07 12:24 UTC, 9037568 commented on distribution/openhabhome/configurations/openhab_default.cfg
> +# IP address of a Http port for megadevice defaut value is 8989
This is not an IP address. Suggested text: "The http port to use for the megadevice binding. (optional, defaults to 8989)"

2016-12-07 12:25 UTC, 9037568 commented on distribution/openhabhome/configurations/openhab_default.cfg
> +#megadevice:httpserverport=8585
This should use the 8989 value that the previous line says is the default.

2017-02-02 02:14 UTC, 9037568 commented on distribution/openhabhome/configurations/openhab_default.cfg
> +# Port number for the web socket. Defaut value is 8989
"Default"

2021-05-16 19:49 UTC, closed without merging