Chromecast binding
openhab/openhab1-addons pull request #4613
Opened 2016-09-01 23:10 UTC by RamenNoodle1

2016-11-04 15:09 UTC, kaikreuzer commented
@RamenNoodle1 FYI, I have created an initial Chromecast binding for openHAB 2: https://github.com/openhab/openhab2-addons/pull/1371
Maybe you'd be interested in helping improving it?

2016-12-10 17:26 UTC, 9037568 requested changes
In addition to the inline comments, please also:
- run all source through the Eclipse formatter
- create a wiki page documenting the setup and use of the binding

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/ChromeCastBindingProvider.java
> +package org.openhab.binding.chromecast;
This file needs the OH copyright/licence header added.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/ChromeCastBindingProvider.java
> + * @since 1.7
@since 1.9.0

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastBinding.java
> +package org.openhab.binding.chromecast.internal;
This file needs the OH copyright/licence header added.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastBinding.java
> + * @since 1.7
@since 1.9.0

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastBinding.java
> +		logger.info("activate!");
Remove this duplicate.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastBinding.java
> +		if(configuration != null){
Remove this block.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastBinding.java
> +						logger.info("execute item: " + itemName + " ip: " + itemConfig.getIP() + " Command: " + itemConfig.getCommand());
Use parameterized logging instead of string concatenation.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastBinding.java
> +						e.printStackTrace();
There should be a logger statement here.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastBinding.java
> +						e.printStackTrace();
There should be a logger statement here.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastBinding.java
> +
There should be a logger statement here.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastBinding.java
> +				} catch (Exception e) {}
There should be a logger statement here.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastBinding.java
> +		logger.info("internalReceiveUpdate");
This should be debug or lower.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastBinding.java
> +		logger.info("internalReceiveUpdate({},{}) is called!", itemName, newState);
This should be debug or lower.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastBinding.java
> +				logger.info("updated " + key);
This should be debug or lower.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastGenericBindingProvider.java
> +package org.openhab.binding.chromecast.internal;
This file needs the OH copyright/licence header added.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastGenericBindingProvider.java
> + * @since 1.7
@since 1.9.0

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastGenericBindingProvider.java
> +		logger.info("containsChromecastInstance!");
This should be debug or lower.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastGenericBindingProvider.java
> +				logger.error("Item configuration direction must be either <, = or >.");
This should be a warn.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastGenericBindingProvider.java
> +			logger.error("Item configuration must have 3 parts");
This should be a warn.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/Constants.java
> +package org.openhab.binding.chromecast.internal;
This file needs the OH copyright/licence header added.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/Constants.java
> +public class Constants {
This class needs a class doc-comment added, including @author and @since tags.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/Helper.java
> +public class Helper {
This class needs a class doc-comment added, including @author and @since tags.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/Helper.java
> +package org.openhab.binding.chromecast.internal;
This file needs the OH copyright/licence header added.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/commands/ApplicationUpdater.java
> +package org.openhab.binding.chromecast.internal.commands;
This file needs the OH copyright/licence header added.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/commands/ApplicationUpdater.java
> +public class ApplicationUpdater implements IUpdater {
This class needs a class doc-comment added, including @author and @since tags.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/commands/IUpdater.java
> +public interface IUpdater {
This class needs a class doc-comment added, including @author and @since tags.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/commands/IUpdater.java
> +package org.openhab.binding.chromecast.internal.commands;
This file needs the OH copyright/licence header added.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/commands/StatusUpdater.java
> +package org.openhab.binding.chromecast.internal.commands;
This file needs the OH copyright/licence header added.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/commands/StatusUpdater.java
> +public class StatusUpdater implements IUpdater {
This class needs a class doc-comment added, including @author and @since tags.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/commands/StatusUpdater.java
> +			logger.error("Status update failed " + e.getMessage());
Use parameterized logging instead of string concatenation.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/commands/StatusUpdater.java
> +		} catch (Exception e){}
There should be a logger statement here.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/commands/VolumeUpdater.java
> +package org.openhab.binding.chromecast.internal.commands;
This file needs the OH copyright/licence header added.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/commands/VolumeUpdater.java
> +public class VolumeUpdater implements IUpdater {
This class needs a class doc-comment added, including @author and @since tags.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/commands/VolumeUpdater.java
> +			logger.info("Chromecast - Faulty state for " + itemConfig.getItemName() + " " + itemConfig.command + " volume");
Use parameterized logging instead of string concatenation.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/commands/VolumeUpdater.java
> +			logger.info("Chromecast - Failed to set state " + itemConfig.getItemName() + " volume");
Use parameterized logging instead of string concatenation.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastBinding.java
> +				if (itemConfig != null &&
Need additional parentheses here to prevent a potential NPE.

2016-12-10 17:26 UTC, 9037568 commented on bundles/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromeCastBinding.java
> +					if(itemConfig != null &&
Need additional parentheses here to prevent a potential NPE.

2021-05-16 19:48 UTC, closed without merging