Added SimpleBinary binding
openhab/openhab1-addons pull request #4809
Opened 2016-11-21 22:36 UTC by docbender

New merged binding pull request ready to review. Original pull request was #3589.

2016-11-22 05:43 UTC, 9037568 requested changes
Thanks for this contribution.

In addition to my inline comments:

Please run all the source through the Eclipse formatter.

Also, in a number of places you are using this construct:
````
       if (logger.isDebugEnabled()) {
            logger.debug("execute() method is called!");
       }
````

This is really not worth doing. The wrapper that checks the logging level should only be used around operations that are expensive. You should consider eliminating these if conditionals anywhere that they're only wrapping a call to logger.x().

2016-11-22 05:43 UTC, 9037568 commented on bundles/binding/org.openhab.binding.simplebinary/src/main/java/org/openhab/binding/simplebinary/internal/SimpleBinaryUART.java
> +        if (LINE_STABILIZATION_TIME > 0) {
This block can never be executed. (The "variable" is always 0)

2016-11-22 05:43 UTC, 9037568 commented on bundles/binding/org.openhab.binding.simplebinary/src/main/java/org/openhab/binding/simplebinary/internal/SimpleBinaryProtocol.java
> +        try {
This try block catches nothing. Why is it here?

2016-11-22 05:43 UTC, 9037568 commented on bundles/binding/org.openhab.binding.simplebinary/src/main/java/org/openhab/binding/simplebinary/internal/SimpleBinaryUART.java
> +                    // TODO: should i call it????
Remove or clarify

2016-11-22 05:43 UTC, 9037568 commented on bundles/binding/org.openhab.binding.simplebinary/META-INF/MANIFEST.MF
> +Service-Component: OSGI-INF/binding.xml, OSGI-INF/genericbindingprovider.xml
Bundle-ActivationPolicy should be set to lazy

2016-11-24 07:11 UTC, docbender commented
Hello, 
thanks for your review.

About _logger_ section. I had a problem in production environment (logger level=WARN) with heavy traffic that sometimes totally random it just crash. I found that it was at _logger.debug(...)_ line.  With condition _logger.isDebugEnabled()_ this crashes disappeared.

Another one. Why should I change year in header? Some files was created in 2015. Same with openhab version. Pull request of this binding was pulled a year ago before 1.8.0 was released.

Finally complete all missing header doc would be long time run.

2016-11-24 07:30 UTC, 9037568 commented
> About logger section.

That's merely advisory. If you don't want to change those, it'll still be fine to merge.

> Another one. Why should I change year in header?

As far as I'm aware, the convention is to have the dates in the copyright headers be up to date based on the year the code is first merged. Certainly the openhab version in the "since" tags needs to be correct. It's also a quick and easy fix.

> Finally complete all missing header doc would be long time run.

If this is about the "@return" doc comments that are incomplete/empty, again I'd call those advisory. I think they'd still be ok to merge if you choose not to clean them up.

2016-11-24 22:48 UTC, docbender commented
Modified code pushed in. Thanks for review

2016-11-25 02:35 UTC, 9037568 commented
Thanks for these updates. There are still a few issues of commented code and copyright dates that need to be addressed, however.

2016-11-25 02:54 UTC, 9037568 commented
I just realized while perusing the wiki page for this binding that you need to add your configuration items to the [openhab_default.cfg](https://github.com/openhab/openhab/blob/master/distribution/openhabhome/configurations/openhab_default.cfg) file.

2016-11-25 14:16 UTC, docbender commented
I pushed openhab_default.cfg update. I also corrected logger strings and the wrong copyright date in OSGI files.

2016-11-25 15:02 UTC, 9037568 commented
Good progress. Still a few left.

2021-01-18 20:08 UTC, closed without merging